apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - image: wil42/playground:v1
          name: 
          command: ["/bin/sh", "-c", "tail -f /dev/null"]
          ports:
            - containerPort: 8888

